name: "java_base_applicaton"
on: 
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name:  Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Verify POM File
      run: ls -la 

    - name: Build with Maven
      run: mvn -B package --file spring-boot-app/pom.xml
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: docker build and push
      run: |
        cd spring-boot-app/
        docker images
        docker build -t parthitk/task:latest .
        docker tag parthitk/task:latest parthitk/task:latest
        docker login -u $ {{ secrets.DOCKERHUB_USERNAME }} -p
        docker push parthitk/task:latest
