name: "java_base_applicaton"
on: 
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name:  Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Verify POM File
      run: ls -la 

    - name: Build with Maven
      run: mvn -B package --file spring-boot-app/pom.xml
    
    - name: Build Docker Image
      run: |
        ls -la 
        cd spring-boot-app/
        docker build -t my-java-app:latest .

    - name: List Docker Images
      run: docker images

    - name: Test Docker Hub Login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    
